import Head from "next/head";
import Link from "next/link";
import HeroSection from "~/components/HeroSection";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex min-h-screen flex-col bg-black px-12 py-8">
        {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          AA
        </h1> */}
        <HeroSection />
      </main>
    </>
  );
}

// items-center justify-center
// bg-gradient-to-b from-[#151345] to-[#15162c]
